export default [
  {
    rank: 1,
    name: "John Doe",
    college: "ABC University",
    courses: ["Computer Science", "Data Science"],
    stream: "Science",
    reviewsCount: 10,
    cashEarned: 250,
    date: "2023-6-20",
  },
  {
    rank: 2,
    name: "Jane Smith",
    college: "XYZ College",
    courses: ["Business Administration", "Marketing"],
    stream: "Commerce",
    reviewsCount: 8,
    cashEarned: 180,
    date: "2023-6-18",
  },
  {
    rank: 3,
    name: "Michael Johnson",
    college: "PQR Institute",
    courses: ["Electrical Engineering"],
    stream: "Engineering",
    reviewsCount: 15,
    cashEarned: 300,
    date: "2023-6-21",
  },
  {
    rank: 4,
    name: "Emily Williams",
    college: "LMN University",
    courses: ["English Literature"],
    stream: "Arts",
    reviewsCount: 5,
    cashEarned: 100,
    date: "2023-5-17",
  },
  {
    rank: 5,
    name: "David Lee",
    college: "DEF College",
    courses: ["Mathematics"],
    stream: "Science",
    reviewsCount: 12,
    cashEarned: 220,
    date: "2023-6-19",
  },
  {
    rank: 6,
    name: "Sarah Johnson",
    college: "GHI University",
    courses: ["Physics"],
    stream: "Science",
    reviewsCount: 7,
    cashEarned: 150,
    date: "2023-6-22",
  },
  {
    rank: 7,
    name: "Robert Davis",
    college: "MNO College",
    courses: ["Computer Science"],
    stream: "Science",
    reviewsCount: 9,
    cashEarned: 200,
    date: "2023-6-16",
  },
  {
    rank: 8,
    name: "Sophia Wilson",
    college: "JKL Institute",
    courses: ["Chemistry"],
    stream: "Science",
    reviewsCount: 6,
    cashEarned: 120,
    date: "2023-6-14",
  },
  {
    rank: 9,
    name: "Olivia Davis",
    college: "UVW College",
    courses: ["Psychology"],
    stream: "Arts",
    reviewsCount: 4,
    cashEarned: 80,
    date: "2023-6-23",
  },
  {
    rank: 10,
    name: "William Johnson",
    college: "RST Institute",
    courses: ["Mechanical Engineering"],
    stream: "Engineering",
    reviewsCount: 11,
    cashEarned: 210,
    date: "2023-6-25",
  },
  {
    rank: 11,
    name: "Ava Anderson",
    college: "CDE University",
    courses: ["Biology", "Chemistry"],
    stream: "Science",
    reviewsCount: 9,
    cashEarned: 190,
    date: "2023-6-26",
  },
  {
    rank: 12,
    name: "James Wilson",
    college: "FGH College",
    courses: ["History", "Political Science"],
    stream: "Arts",
    reviewsCount: 7,
    cashEarned: 130,
    date: "2023-6-24",
  },
  {
    rank: 13,
    name: "Ella Thompson",
    college: "IJK Institute",
    courses: ["Environmental Science"],
    stream: "Science",
    reviewsCount: 6,
    cashEarned: 110,
    date: "2023-6-27",
  },
  {
    rank: 14,
    name: "Benjamin Martinez",
    college: "LMN University",
    courses: ["Computer Engineering"],
    stream: "Engineering",
    reviewsCount: 13,
    cashEarned: 240,
    date: "2023-6-29",
  },
  {
    rank: 15,
    name: "Mia Thompson",
    college: "OPQ College",
    courses: ["Economics"],
    stream: "Commerce",
    reviewsCount: 5,
    cashEarned: 100,
    date: "2023-6-28",
  },
  {
    rank: 16,
    name: "Alexander Garcia",
    college: "RST Institute",
    courses: ["Civil Engineering"],
    stream: "Engineering",
    reviewsCount: 9,
    cashEarned: 200,
    date: "2023-5-30",
  },
  {
    rank: 17,
    name: "Scarlett Adams",
    college: "UVW College",
    courses: ["Fine Arts"],
    stream: "Arts",
    reviewsCount: 3,
    cashEarned: 60,
    date: "2023-7-2",
  },
  {
    rank: 18,
    name: "Liam Wilson",
    college: "XYZ College",
    courses: ["Finance"],
    stream: "Commerce",
    reviewsCount: 10,
    cashEarned: 230,
    date: "2023-7-1",
  },
  {
    rank: 19,
    name: "Chloe Moore",
    college: "ABC University",
    courses: ["Statistics"],
    stream: "Science",
    reviewsCount: 8,
    cashEarned: 170,
    date: "2023-5-3",
  },
  {
    rank: 20,
    name: "Henry Baker",
    college: "IJK Institute",
    courses: ["Mechatronics"],
    stream: "Engineering",
    reviewsCount: 14,
    cashEarned: 260,
    date: "2023-5-4",
  },
];
