export default [
  {
    scholarshipName: "Tata Scholarship - Cornell University",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "College-Specific",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 20,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Ontario Trillium Scholarship",
    internationalStudentEligible: "Yes",
    amount: "$28,961",
    type: "Merit-Based",
    levelOfStudy: "Doctorate",
    numberOfScholarships: 75,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Ontario Graduate Scholarship",
    internationalStudentEligible: "Yes",
    amount: "$10,847",
    type: "College-Specific",
    levelOfStudy: "Doctorate",
    numberOfScholarships: 22,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Charles Wallace India Trust",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "Awards",
    levelOfStudy: "N/A",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "GREAT Scholarship",
    internationalStudentEligible: "Yes",
    amount: "$12,499",
    type: "College-Specific",
    levelOfStudy: "Master",
    numberOfScholarships: 103,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Felix Scholarships",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "College-Specific",
    levelOfStudy: "Doctorate",
    numberOfScholarships: 20,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Deutschland Stipendium Program",
    internationalStudentEligible: "Yes",
    amount: "$4,363",
    type: "College-Specific",
    levelOfStudy: "Bachelor",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Australian Government Research",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "Merit-Based",
    levelOfStudy: "Doctorate",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "DAAD Scholarships",
    internationalStudentEligible: "Yes",
    amount: "$888",
    type: "Merit-Based",
    levelOfStudy: "Doctorate",
    numberOfScholarships: 100000,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Australia Awards Scholarship",
    internationalStudentEligible: "Yes",
    amount: "$12,499",
    type: "Awards",
    levelOfStudy: "N/A",
    numberOfScholarships: 103,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Stanford Reliance Dhirubhai",
    internationalStudentEligible: "Yes",
    amount: "$150,000",
    type: "College-Specific",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 3,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Inlaks Shivdasani Foundation",
    internationalStudentEligible: "Yes",
    amount: "$100,000",
    type: "Merit-Based",
    levelOfStudy: "Doctorate",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Rotary Foundation Scholarships",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "Company-Sponsored",
    levelOfStudy: "Master",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Hornby Scholarships",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "College-Specific",
    levelOfStudy: "Master",
    numberOfScholarships: 10,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Heinrich Boll Scholarships",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "Company-Sponsored",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 1200,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Tata Scholarship - Cornell university",
    internationalStudentEligible: "Yes",
    amount: "Variable amount",
    type: "College specific",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 20,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Australia Awards Scholarship",
    internationalStudentEligible: "Yes",
    amount: "Variable Amount",
    type: "Merit-Based",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 1985,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Stanford Reliance Dhirubhai",
    internationalStudentEligible: "Yes",
    amount: "$150,000",
    type: "College-Specific",
    levelOfStudy: "Bachelor",
    numberOfScholarships: 3,
    viewMore: "",
    applyNow: "",
  },
  {
    scholarshipName: "Inlaks Shivdasani Foundation",
    internationalStudentEligible: "Yes",
    amount: "$100,000",
    type: "Merit-Based",
    levelOfStudy: "Doctorate",
    numberOfScholarships: "N/A",
    viewMore: "",
    applyNow: "",
  },
];
